INSERT INTO City (name) VALUES ('Beograd');
INSERT INTO City (name) VALUES ('Bor');
INSERT INTO City (name) VALUES ('Valjevo');
INSERT INTO City (name) VALUES ('Vranje');
INSERT INTO City (name) VALUES ('Vršac');
INSERT INTO City (name) VALUES ('Zaječar');
INSERT INTO City (name) VALUES ('Zrenjanin');
INSERT INTO City (name) VALUES ('Jagodina');
INSERT INTO City (name) VALUES ('Kikinda');
INSERT INTO City (name) VALUES ('Kragujevac');
INSERT INTO City (name) VALUES ('Kraljevo');
INSERT INTO City (name) VALUES ('Kruševac');
INSERT INTO City (name) VALUES ('Leskovac');
INSERT INTO City (name) VALUES ('Loznica');
INSERT INTO City (name) VALUES ('Niš');
INSERT INTO City (name) VALUES ('Novi Pazar');
INSERT INTO City (name) VALUES ('Novi Sad');
INSERT INTO City (name) VALUES ('Pančevo');
INSERT INTO City (name) VALUES ('Pirot');
INSERT INTO City (name) VALUES ('Požarevac');
INSERT INTO City (name) VALUES ('Priština');
INSERT INTO City (name) VALUES ('Prokuplje');
INSERT INTO City (name) VALUES ('Smederevo');
INSERT INTO City (name) VALUES ('Sombor');
INSERT INTO City (name) VALUES ('Sremska Mitrovica');
INSERT INTO City (name) VALUES ('Subotica');
INSERT INTO City (name) VALUES ('Užice');
INSERT INTO City (name) VALUES ('Čačak');
INSERT INTO City (name) VALUES ('Šabac');
